export const PROJECTS = [
  {
    id: "tribes",
    title: "Tribes of Valrheim",
    subtitle: "3D Action RPG Game",
    type: "Game",
    typeColor: "#ff6b35",
    description:
      "A fully-featured 3D action RPG built in Godot Engine. Developed gameplay systems, core mechanics, state management, player interactions, and polished HUD/UI components. Created and optimized 3D assets in Blender for environments and characters.",
    tech: [
      "GDScript",
      "Godot Engine",
      "Blender",
      "3D Modeling",
      "State Management",
    ],
    highlights: [
      "Gameplay systems & core mechanics",
      "Interactive HUDs & menus",
      "3D asset creation in Blender",
      "Full game flow logic",
    ],
    emoji: "⚔️",
    featured: true,
    images: ["/public/assets/Tribes.png"],
  },
  {
    id: "bisdakids",
    title: "BisadaKids",
    subtitle: "Mobile Educational Game",
    type: "Mobile App",
    typeColor: "#a78bfa",
    description:
      "A mobile hidden-object game built for Filipino kids, featuring Bisaya language content to make learning fun and culturally grounded. Players search for hidden objects across illustrated scenes while picking up Bisaya vocabulary naturally.",
    tech: [
      "Mobile Dev",
      "Game Design",
      "Bisaya Language",
      "Hidden Object Mechanics",
    ],
    highlights: [
      "Hidden object gameplay loop",
      "Bisaya language integration",
      "Kid-friendly UI/UX",
      "Educational content design",
    ],
    emoji: "🎮",
    featured: true,
    images: [
      "/public/assets/BMain.png",
      "/public/assets/B2.png",
      "/public/assets/B3.png",
      "/public/assets/B1.png",
    ],
  },
  {
    id: "bisdakids-admin",
    title: "BisadaKids Admin",
    subtitle: "Web Dashboard",
    type: "Web App",
    typeColor: "#38bdf8",
    description:
      "The companion admin panel for the BisadaKids mobile game. A web-based dashboard for managing game content, monitoring player data, and updating educational assets without touching the codebase.",
    tech: ["React", "Web Dev", "Dashboard", "REST API", "Database"],
    highlights: [
      "Content management system",
      "Player data monitoring",
      "Asset management",
      "Admin authentication",
    ],
    emoji: "🖥️",
    featured: false,
    images: ["/public/assets/BAdmin.png"],
  },
  {
    id: "caregraver",
    title: "CareGraver",
    subtitle: "Cemetery Management System",
    type: "Web App",
    typeColor: "#00ff88",
    description:
      "A web platform for cemetery plot management where users can browse available slots on an interactive map, reserve a plot, and purchase memorial services and products — bringing a traditionally offline process entirely online.",
    tech: ["Web Dev", "JavaScript", "Database", "REST API", "UI/UX"],
    highlights: [
      "Interactive slot picker",
      "Online reservations",
      "Products & services catalog",
      "Admin management panel",
    ],
    emoji: "🪦",
    featured: true,
    images: [
      "/public/assets/C1.png",
      "/public/assets/C2.png",
      "/public/assets/C3.png",
      "/public/assets/C4.png",
      "/public/assets/C5.png",
      "/public/assets/C6.png",
    ],
  },
  {
    id: "rfid",
    title: "RFID Attendance System",
    subtitle: "Hardware + Software Integration",
    type: "IoT / Web",
    typeColor: "#fbbf24",
    description:
      "A smart attendance system where students tap their RFID-enabled ID cards on a reader and attendance is automatically logged into the database in real time — eliminating manual recording and streamlining school administration.",
    tech: ["RFID", "Hardware Integration", "Database", "Python", "REST API"],
    highlights: [
      "Real-time RFID card detection",
      "Auto database logging",
      "Student record management",
      "Admin dashboard",
    ],
    emoji: "📡",
    featured: false,
    images: [
      "/public/assets/RFID1.jpg",
      "/public/assets/RFID3.png",
      "/public/assets/RFID2.png",
    ],
  },
  {
    id: "sports-store",
    title: "Sports Store",
    subtitle: "E-Commerce Web App",
    type: "Web App",
    typeColor: "#38bdf8",
    description:
      "A full-featured online sports equipment store with product listings, cart management, and checkout flow. Designed with a clean, performance-focused UI for sports enthusiasts.",
    tech: ["React", "Node.js", "Database", "CSS", "REST API"],
    highlights: [
      "Product catalog & filtering",
      "Shopping cart system",
      "Checkout flow",
      "Responsive design",
    ],
    emoji: "🏀",
    featured: false,
  },
  {
    id: "valentines",
    title: "Valentine's Surprise",
    subtitle: "A Love Letter in Code",
    type: "Fun Project",
    typeColor: "#f472b6",
    description:
      "A personal passion project — a quirky, lovingly crafted 'Will you be my Valentine?' website made for my partner. Not so cute, 100% heartfelt. Because nothing says 'I love you' like deploying a whole website.",
    tech: ["HTML", "CSS", "JavaScript", "Love", "Chaos"],
    highlights: [
      "Interactive yes/no buttons (the no button runs away)",
      "Surprise animations",
      "Custom design",
      "Built with ❤️",
    ],
    emoji: "💌",
    featured: false,
    images: ["/public/assets/V1.png", "/public/assets/V2.png"],
  },
];
